using Content.Client.UserInterface.Controls;
using Content.Shared._ES.EmergencyAccess.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.EmergencyAccess.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESEmergencyAccessConsoleWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;

    public event Action<string>? OnSearchButtonPressed;
    public event Action? OnToggleButtonPressed;

    public ESEmergencyAccessConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.IsValid = input => input.Length <= 5;

        SearchButton.OnPressed += _ =>
        {
            OnSearchButtonPressed?.Invoke(SearchBar.Text);
        };

        ToggleButton.OnPressed += _ =>
        {
            OnToggleButtonPressed?.Invoke();
        };
    }

    public void Update(EntityUid uid, bool initial = false)
    {
        if (!_entityManager.TryGetComponent<ESEmergencyAccessConsoleComponent>(uid, out var comp))
            return;

        if (initial)
            SearchBar.Text = comp.CurrentKey;

        NotFoundLabel.Visible = !comp.HasValidState;
        InfoBox.Visible = comp.HasValidState;

        var key = string.IsNullOrWhiteSpace(comp.CurrentKey) ? "null" : comp.CurrentKey;
        NotFoundLabel.Text = Loc.GetString("es-emergency-access-ui-no-valid-airlock", ("key", key));

        AccessKeyLabel.Text = Loc.GetString("es-emergency-access-ui-key-status", ("key", key.ToUpperInvariant()));

        EmergencyAccessStatusLabel.Text = comp.EmergencyEnabled
            ? Loc.GetString("es-emergency-access-ui-emergency-access-status-enabled")
            : Loc.GetString("es-emergency-access-ui-emergency-access-status-disabled");

        BoltStatusLabel.Text = comp.BoltEnabled
            ? Loc.GetString("es-emergency-access-ui-bolt-status-enabled")
            : Loc.GetString("es-emergency-access-ui-bolt-status-disabled");

        PowerStatusLabel.Text = comp.PowerEnabled
            ? Loc.GetString("es-emergency-access-ui-power-status-enabled")
            : Loc.GetString("es-emergency-access-ui-power-status-disabled");

        ToggleButton.Disabled = !comp.PowerEnabled;
    }
}

